>>> matrix_mul = __import__('100-matrix_mul').matrix_mul

>>> matrix_mul()
Traceback (most recent call last):
TypeError: matrix_mul() missing 2 required positional arguments: 'm_a' and 'm_b'
>>> matrix_mul([[1, 2, 3]])
Traceback (most recent call last):
TypeError: matrix_mul() missing 1 required positional argument: 'm_b'
>>> matrix_mul([[1, 2, 3]], [[1], [2], [3]], [4, 5, 6])
Traceback (most recent call last):
TypeError: matrix_mul() takes 2 positional arguments but 3 were given
>>> matrix_mul(1, 2)
Traceback (most recent call last):
TypeError: m_a must be a list
>>> matrix_mul([], 2)
Traceback (most recent call last):
TypeError: m_b must be a list
>>> matrix_mul([1, 2], [3, 4])
Traceback (most recent call last):
TypeError: m_a must be a list of lists
>>> matrix_mul([[]], [3, 4])
Traceback (most recent call last):
TypeError: m_b must be a list of lists
>>> matrix_mul([], [])
Traceback (most recent call last):
ValueError: m_a can't be empty
>>> matrix_mul([[]], [])
Traceback (most recent call last):
ValueError: m_a can't be empty
>>> matrix_mul([[1, 2], [3, 4]], [])
Traceback (most recent call last):
ValueError: m_b can't be empty
>>> matrix_mul([[1, 2], [3, 4]], [[]])
Traceback (most recent call last):
ValueError: m_b can't be empty
>>> matrix_mul([[1, 2], [3, 'd']], [[1, 2], [3, 4]])
Traceback (most recent call last):
TypeError: m_a should contain only integers or floats
>>> matrix_mul([[1, 2], [3, 4]], [[1, 2], ['c', 4]])
Traceback (most recent call last):
TypeError: m_b should contain only integers or floats
>>> matrix_mul([[1, 2, 3], [4, 5], [6, 7, 8]], [[1]])
Traceback (most recent call last):
TypeError: each row of m_a must should be of the same size
>>> matrix_mul([[1, 2, 3], [4, 5, 6]], [[1, 2], [3, 4, 5], [6, 7, 8]])
Traceback (most recent call last):
TypeError: each row of m_b must should be of the same size
>>> matrix_mul([[1, 2, 3]], [[1, 2], [3, 4]])
Traceback (most recent call last):
ValueError: m_a and m_b can't be multiplied
>>> matrix_mul([[1, 2, 3], [4, 5, 6]], [[1, 2], [3, 4], [5, 6], [7, 8]])
Traceback (most recent call last):
ValueError: m_a and m_b can't be multiplied
